language: python

# https://docs.travis-ci.com/user/languages/python#running-python-tests-on-multiple-operating-systems
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
      script:       # Additionally test docs
        - make test
        - make examples
        - make docs
    - name: "Python 3.8 on Linux"
      os: linux
      python: 3.8
    - name: "Python 3.6 on macOS"
      os: osx
      language: shell       # 'language: python' isn't directly supported by Travis CI for osx
      addons:
        homebrew:
          packages: python3
      before_install:
        - python3 -m venv "$HOME/venv"
        - source "$HOME/venv/bin/activate"
    - name: "Python 3.8 on Windows"
      os: windows
      language: shell       # 'language: python' isn't directly supported by Travis CI for windows
      before_install:
        - choco install python3 --version 3.8
        - choco install make
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install -r dev-requirements.txt

script:
  - make test
