[tool.black]
line-length = 99
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.ruff]
line-length = 99
src = ["deon/**/*.py", "tests/**/*.py", "docs/**/*.py"]

[tool.ruff.lint]
select = [
  "E", # Pycodestyle
  "F", # Pyflakes
  "I", # isort
  "W", # Pycodestyle
]
ignore = ["E501"]
unfixable = ["F"]

[tool.ruff.lint.isort]
known-first-party = ["deon", "assets"]
force-sort-within-sections = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=deon --cov-report=term --cov-report=html --cov-report=xml --cov-append"
testpaths = ["tests"]

[tool.coverage.run]
source = ["deon"]

[tool.coverage.report]
exclude_also = [
  "if TYPE_CHECKING:",
]
